package com.core.appservices.serializers;

public enum Serializers {
    // JSON
    JSON_CLIENT,
    JSON_ESPA_CLIENT,
    JSON_BOOK,
    JSON_ESPA_BOOK,
    JSON_ORDER,
    JSON_ESPA_ORDER,
    JSON_COURSES,
    JSON_ESPA_COURSES,
    JSON_EMPLOYEE,
    JSON_ESPA_EMPLOYEE,
    // XML
    XML_CLIENT,
    XML_ESPA_CLIENT,
    XML_BOOK,
    XML_ESPA_BOOK,
    XML_ORDER,
    XML_ESPA_ORDER,
    XML_COURSES,
    XML_ESPA_COURSES,
    XML_EMPLOYEE,
    XML_ESPA_EMPLOYEE
}